const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const api=require('../demo/api/hut-prices'),base=path.join(__dirname,'../demo'),galassi=fs.readFileSync(path.join(__dirname,'fixtures/galassi-prices.html'),'utf8'),biella=fs.readFileSync(path.join(__dirname,'fixtures/biella-prices.html'),'utf8');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']}),p=await browser.newPage({viewport:{width:1280,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));let checks=0,fail=false,hold=false,release,held=false;const previousFetch=global.fetch,cinque=fs.readFileSync(path.join(__dirname,'fixtures/cinque-prices.html'),'utf8');
 global.fetch=async(url)=>new Response(fail?'broken layout':url.includes('galassi')?galassi:url.includes('5torri')?cinque:biella,{headers:{'content-type':'text/html'}});
 await p.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='demo.test')return route.abort();if(u.pathname==='/api/hut-prices'){checks++;if(hold&&u.searchParams.get('hut')==='osm-relation-19526395'){held=true;await new Promise(resolve=>release=resolve);}const res={setHeader(){},status(code){this.code=code;return this;},json(data){this.data=data;return this;}};await api({method:'GET',query:{hut:u.searchParams.get('hut')}},res);try{return await route.fulfill({status:res.code,json:res.data});}catch{return;}}
 if(u.pathname==='/api/catalogue')return route.fulfill({json:JSON.parse(fs.readFileSync(path.join(base,'data/dolomites.json')))});if(u.pathname==='/api/ors')return route.fulfill({json:{configured:true}});const name=u.pathname==='/'?'index.html':u.pathname.slice(1),file=path.join(base,name);return fs.existsSync(file)?route.fulfill({body:fs.readFileSync(file),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/html'}):route.abort();});
 const open=async name=>{await p.locator('#hut-search').fill(name);await p.locator('.hut').first().click();};
 await p.goto('https://demo.test');await p.waitForFunction(()=>stopDraftReady&&huts.length===296);await open('Pietro Galassi');await p.waitForFunction(()=>document.querySelectorAll('.hut-rates li').length===6);assert.match(await p.locator('#hut-live-prices').innerText(),/2026.*not confirmed rates for your 2027 trip/s);assert.match(await p.locator('#hut-live-prices').innerText(),/No package has been selected/);assert.equal(await p.evaluate(()=>huts.find(h=>h.id==='osm-relation-19526395').price),null);
 await p.waitForFunction(async()=>Boolean(await read('hut-prices-osm-relation-19526395')));await p.locator('#detail .close').click();await open('Pietro Galassi');assert.equal(await p.locator('.hut-rates li').count(),6);assert.equal(checks,1);await p.locator('#detail .close').click();
 await p.locator('.hut-filters summary').click();await p.locator('#hut-price-filter').selectOption('50');await p.locator('#hut-include-unknown-price').uncheck();assert.equal(await p.locator('.hut').count(),1);assert.match(await p.locator('.hut').innerText(),/6 published rates/);await p.locator('#reset-hut-filters').click();
 await p.evaluate(async()=>{const id='osm-relation-19526395',old=await read('hut-prices-'+id);old.checkedAt=new Date(Date.now()-8*3600000).toISOString();await write('hut-prices-'+id,old);});fail=true;await p.reload();await p.waitForFunction(()=>stopDraftReady&&huts.length===296);await open('Pietro Galassi');await p.waitForFunction(()=>document.querySelector('#hut-live-prices')?.textContent.includes('may be outdated'));assert.equal(await p.locator('.hut-rates li').count(),6);await p.locator('#detail .close').click();
 fail=false;hold=true;await open('Pietro Galassi');await p.waitForFunction(()=>document.querySelector('[data-price-check]'));assert(held);await p.locator('#detail .close').click();await open('Biella');await p.waitForFunction(()=>document.querySelectorAll('.hut-rates li').length===1);release();await p.waitForTimeout(100);assert.match(await p.locator('#hut-live-prices').innerText(),/€90.00/);assert.doesNotMatch(await p.locator('#hut-live-prices').innerText(),/Under 25/);assert.match(await p.locator('#hut-live-prices').innerText(),/not stated a rate year/);
 await p.locator('#detail .close').click();await open('Cinque Torri');await p.waitForFunction(()=>document.querySelectorAll('.hut-rates li').length===4);assert.match(await p.locator('#hut-live-prices').innerText(),/Private room/);assert.match(await p.locator('#hut-live-prices').innerText(),/Shared dormitory/);assert.match(await p.locator('#hut-live-prices').innerText(),/2026.*not confirmed rates for your 2027 trip/s);assert.doesNotMatch(await p.locator('#hut-live-prices').innerText(),/€5.00|€25.00/);
 await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);global.fetch=previousFetch;await browser.close();console.log('PASS: open hut checks all published rates through API/parser; membership/year labels; no default; cache/reload; failed refresh preserves rates; budget matches packages; late response cannot overwrite another hut; mobile layout.');})().catch(e=>{console.error(e);process.exit(1)});
