const test=require('node:test'),assert=require('node:assert/strict'),core=require('../demo/itinerary-core');
const huts=[{id:'far',name:'Far',lat:46.55,lng:12.1},{id:'near',name:'Near',lat:46.501,lng:12},{id:'start',name:'Start',lat:46.5,lng:12}];
test('proximity ordering uses starting hut and preserves original catalogue',()=>{const sorted=core.nearby(huts,huts[2]);assert.deepEqual(sorted.map(h=>h.id),['start','near','far']);assert.deepEqual(huts.map(h=>h.id),['far','near','start']);assert.equal(sorted[0].proximityM,0);assert(sorted[1].proximityM>100&&sorted[1].proximityM<120);assert.deepEqual(core.nearby(huts,huts[0]).map(h=>h.id),['far','near','start']);});
test('rest days shift dates across month boundaries without stage metrics',()=>{const stages=[{start:{id:'a'},end:{id:'b',name:'B'},distanceM:1000,hours:1,ascentM:100,restAfter:true},{start:{id:'b'},end:{id:'c'},distanceM:2000,hours:2,ascentM:200}];const days=core.days(stages,'2027-07-31');assert.deepEqual(days.map(d=>[d.type,d.date]),[['hike','2027-07-31'],['rest','2027-08-01'],['hike','2027-08-02']]);assert.deepEqual(core.totals(stages),{distanceM:3000,hours:3,ascentM:300,calendarDays:3});assert.equal(core.continuous(stages),true);assert.equal(core.continuous([{...stages[0],end:{id:'z'}},stages[1]]),false);});
test('daily limit checks distinguish exceeded limits from missing metrics',()=>{assert.equal(core.limits({distanceM:13000,hours:7,ascentM:1000},{distance:12,hours:6,ascent:900}).length,3);const unknown=core.limits({distanceM:1000},{distance:12,hours:6,ascent:900});assert.equal(unknown.length,2);assert(unknown.every(w=>w.includes('cannot be checked')));assert.equal(core.totals([{distanceM:1000}]).hours,null);});

test('trip totals sum complete estimates and retain incomplete totals when any day lacks a metric',()=>{const stages=[{distanceM:3000,hours:2,ascentM:400,restAfter:true},{distanceM:5000,hours:3.5,ascentM:700}];assert.deepEqual(core.totals(stages),{distanceM:8000,hours:5.5,ascentM:1100,calendarDays:3});assert.deepEqual(core.totals([...stages,{distanceM:2000}]),{distanceM:10000,hours:null,ascentM:null,calendarDays:4});});
test('overnight status belongs to a particular hut, arrival date and number of nights',()=>{const stages=[{start:{id:'a'},end:{id:'b'},distanceM:1000,overnight:{status:'confirmed',hutId:'b',date:'2027-07-31',nights:1,notes:'Operator reference ABC'}}];assert.equal(core.overnight(stages,0,'2027-07-31').status,'confirmed');assert.equal(core.overnight(stages,0,'2027-08-01').status,'not_contacted');assert.equal(core.overnight(stages,0,'2027-08-01').needsReview,true);assert.equal(core.overnight([{...stages[0],restAfter:true}],0,'2027-07-31').needsReview,true);assert.equal(core.overnight([{...stages[0],end:{id:'c'}}],0,'2027-07-31').needsReview,true);assert.equal(core.overnight(stages,0,'2027-08-01').notes,'Operator reference ABC');});
test('rest days shift following bookings and repeated hut visits keep separate statuses',()=>{const stages=[{start:{id:'a'},end:{id:'b'},restAfter:true},{start:{id:'b'},end:{id:'a'},overnight:{status:'requested',hutId:'a',date:'2027-08-02',nights:1,notes:''}},{start:{id:'a'},end:{id:'b'}}];assert.equal(core.overnight(stages,1,'2027-07-31').status,'requested');assert.equal(core.overnight(stages,2,'2027-07-31').status,'not_contacted');assert.equal(core.overnight([{...stages[0],restAfter:false},...stages.slice(1)],1,'2027-07-31').needsReview,true);});
test('overnight backup validation accepts legacy trips and rejects invalid metadata',()=>{assert.equal(core.validOvernight(undefined),true);const valid={status:'requested',hutId:'a',date:'2027-07-31',nights:2,notes:'Contacted operator'};assert.equal(core.validOvernight(valid),true);for(const change of [{status:'booked_by_system'},{nights:0},{notes:'x'.repeat(2001)},{date:'unknown'},{notes:42}])assert.equal(core.validOvernight({...valid,...change}),false);});
test('numeric hut elevations handle formatted thousands without misclassifying huts',()=>{assert.equal(core.hutElevation('2,137 m'),2137);assert.equal(core.hutElevation('2137.5 m'),2137.5);assert.equal(core.hutElevation(1800),1800);assert(Number.isNaN(core.hutElevation('Elevation not recorded')));assert(Number.isNaN(core.hutElevation(null)));});
test('overnight metadata and rest days follow hut visits when inserting or reordering stops',()=>{const old=[{start:{id:'a'},end:{id:'b'},restAfter:true,overnight:{notes:'B',hutId:'b'},review:{notes:'AB'}},{start:{id:'b'},end:{id:'c'},overnight:{notes:'C',hutId:'c'},review:{notes:'BC'}}];const reordered=[{start:{id:'a'},end:{id:'c'}},{start:{id:'c'},end:{id:'b'}}];const result=core.reconcileStages(reordered,old);assert.equal(result[0].overnight.notes,'C');assert.equal(result[1].overnight.notes,'B');assert.equal(result[1].restAfter,true);assert.equal(result[0].review.notes,'BC');const inserted=core.reconcileStages([{start:{id:'a'},end:{id:'x'}},{start:{id:'x'},end:{id:'b'}}],old);assert.equal(inserted[0].overnight,undefined);assert.equal(inserted[1].overnight.notes,'B');const replaced=core.reconcileStages([{start:{id:'a'},end:{id:'x'}}],old);assert.equal(replaced[0].overnight.hutId,'b');assert.equal(replaced[0].restAfter,false);assert.equal(old[0].overnight.notes,'B');});
test('repeated hut visits keep separate notes and explicit rest edits win',()=>{const old=[{start:{id:'a'},end:{id:'b'},overnight:{notes:'first'},review:{notes:'first leg'},restAfter:true},{start:{id:'b'},end:{id:'a'}},{start:{id:'a'},end:{id:'b'},overnight:{notes:'second'},review:{notes:'second leg'}}];const result=core.reconcileStages(old.map(s=>({...s,restAfter:false})),old,false);assert.equal(result[0].overnight.notes,'first');assert.equal(result[2].overnight.notes,'second');assert.equal(result[0].review.notes,'first leg');assert.equal(result[2].review.notes,'second leg');assert.equal(result[0].restAfter,false);});
test('calendar dates reject normalized invalid days and handle leap years',()=>{assert.equal(core.validDate('2027-02-31'),false);assert.equal(core.validDate('2027-02-29'),false);assert.equal(core.validDate('2028-02-29'),true);assert.equal(core.validDate('2027-04-31'),false);assert.equal(core.dateAt('2028-02-29',1),'2028-03-01');assert.equal(core.dateAt('2027-02-31',1),'');assert.equal(core.validOvernight({status:'confirmed',hutId:'a',date:'2027-02-31',nights:1,notes:''}),false);});
