const {test}=require('node:test');const assert=require('node:assert/strict');const handler=require('../demo/api/ors');
const start=[12.0547744,46.508098],end=[12.0465889,46.5080688];
function fixture(){return {features:[{geometry:{type:'LineString',coordinates:[[...start,2149],[...end,2231]]},properties:{summary:{distance:680,duration:1000},ascent:82,descent:0,extras:{traildifficulty:{values:[[0,1,2]]}}}}]};}
test('retains provider route geometry and estimated metrics',()=>{const result=handler.normalize(fixture(),start,end,'mountain_hiking');assert.equal(result.provider,'ors');assert.equal(result.distanceM,680);assert.equal(result.ascentM,82);assert.equal(result.startGapM,0);assert.equal(result.verification,'mapped_trails_unreviewed_hut_access');});
test('rejects routes above requested recorded difficulty',()=>assert.throws(()=>handler.normalize(fixture(),start,end,'hiking'),/difficulty/));
test('rejects excessive provider snapping and invalid geometry',()=>{const data=fixture();data.features[0].geometry.coordinates[0]=[12,46.5,2100];assert.throws(()=>handler.normalize(data,start,end,'mountain_hiking'),/100 m/);data.features[0].geometry.coordinates[0]=[Infinity,46.5,2100];assert.throws(()=>handler.normalize(data,start,end,'mountain_hiking'),/invalid route/);});
test('missing difficulty remains explicitly unknown',()=>{const data=fixture();delete data.features[0].properties.extras;assert.equal(handler.normalize(data,start,end,'mountain_hiking').unknownDifficulty,1);});
test('status reports configuration without returning a credential',async()=>{const old=process.env.ORS_API_KEY;process.env.ORS_API_KEY='test-placeholder-not-a-real-key';try{let response;await handler({method:'GET',query:{}},{status(){return this},json(value){response=value;return this}});assert.equal(response.configured,true);assert.equal(JSON.stringify(response).includes(process.env.ORS_API_KEY),false);}finally{if(old===undefined)delete process.env.ORS_API_KEY;else process.env.ORS_API_KEY=old;}});
test('missing ascent and descent metadata derive from original ORS elevations while provider time stays intact',()=>{const data=fixture(),p=data.features[0].properties;delete p.ascent;delete p.descent;data.features[0].geometry.coordinates=[[...start,2100],[(start[0]+end[0])/2,start[1],2250],[...end,2200]];const route=handler.normalize(data,start,end,'mountain_hiking');assert.equal(route.ascentM,150);assert.equal(route.descentM,50);assert.equal(route.hours,1000/3600);assert.deepEqual(route.elevation,[2100,2250,2200]);});
test('all ORS vertex elevations stay aligned with geometry for profiles and GPX',()=>{const data=fixture();data.features[0].geometry.coordinates=Array.from({length:100},(_,i)=>[start[0]+(end[0]-start[0])*i/99,start[1]+(end[1]-start[1])*i/99,2100+i]);const route=handler.normalize(data,start,end,'mountain_hiking');assert.equal(route.elevation.length,route.geometry.length);assert.equal(route.elevation.length,100);});
test('Any difficulty accepts all supported recorded SAC ranks and still reports unknown metadata',()=>{const data=fixture();data.features[0].properties.extras.traildifficulty.values=[[0,1,6]];assert.equal(handler.normalize(data,start,end,'any').provider,'ors');assert.throws(()=>handler.normalize(data,start,end,'mountain_hiking'),/difficulty/);data.features[0].properties.extras.traildifficulty.values=[[0,1,0]];assert.equal(handler.normalize(data,start,end,'any').unknownDifficulty,1);});
