const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1280,height:850}});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='demo.test')return r.abort();if(u.pathname==='/api/catalogue'){const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../demo/data/dolomites.json')));return r.fulfill({json:data});}if(u.pathname==='/api/elevation')return r.fulfill({status:503,json:{error:'Unavailable'}});const name=u.pathname==='/'?'index.html':u.pathname.slice(1);const file=path.join(path.join(__dirname,'../demo'),name);if(fs.existsSync(file))return r.fulfill({body:fs.readFileSync(file),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/html'});return r.abort();});
 await p.goto('https://demo.test');await p.waitForFunction(()=>storageReady&&localNetwork&&huts.length===46);assert.equal(await p.locator('.hut').count(),46);assert.equal(await p.locator('.hut-marker').count(),46);
 await p.locator('#hut-search').fill('averau');assert.equal(await p.locator('.hut').count(),1);await p.locator('#hut-search').fill('');
 await p.locator('#destination').selectOption('cinque');await p.waitForFunction(()=>huts.length===4);await p.locator('#new-trip').click();assert.equal(await p.locator('#planner').isVisible(),false);await p.locator('[data-stop="0"]').selectOption('cinque');
 for(const id of ['scoiattoli','averau','nuvolau']){await p.locator('#append-hut').click();await p.locator('[data-stop]').last().selectOption(id);}
 assert.equal(await p.locator('[data-stop]').count(),4);await p.locator('#calculate-route').click();await p.waitForFunction(()=>!planBusy&&plannedStages.length===3);assert.equal(await p.locator('.stage-row').count(),3);
 await p.locator('[data-stage="0"]').click();assert.match(await p.locator('#route-result').innerText(),/0.67 km/);await p.locator('.route-evidence summary').click();assert.match(await p.locator('#route-result').innerText(),/Final hut approaches excluded/);
 await p.waitForTimeout(600);const route=p.locator('.trip-route').first();const point=await p.evaluate(()=>{const s=plannedStages[0].geometry,c=s[Math.floor(s.length/2)],point=map.latLngToContainerPoint([c[1],c[0]]),rect=$('map').getBoundingClientRect();return {x:point.x+rect.x,y:point.y+rect.y};});await p.mouse.move(point.x,point.y);await p.locator('.route-tooltip').waitFor();assert.match(await p.locator('.route-tooltip').innerText(),/0.67 km/);assert.equal(await p.locator('.trip-route[stroke="#efab32"]').count(),1);await p.mouse.move(0,0);await p.mouse.click(point.x,point.y);assert.match(await p.locator('#route-result').innerText(),/DAY DETAILS/);assert.equal(await p.locator('#add-stage').isVisible(),false);
 await p.locator('[data-stage="2"]').click();assert.match(await p.locator('#route-result').innerText(),/Nuvolau/);await p.locator('#save-route-plan').click();await p.waitForFunction(()=>trips.length===1);assert.equal(await p.evaluate(()=>trips[0].stages.length),3);
 await p.locator('#build-mode').click();
 await p.locator('.route-options summary').click();const oldGeometry=await p.evaluate(()=>JSON.stringify(plannedStages));let calls=0;await p.route('**/api/ors?**',async r=>{calls++;if(calls===2)return r.fulfill({status:503,json:{error:'Routing temporarily unavailable'}});const fixture=await p.evaluate(()=>({...plannedStages[0],provider:'ors'}));return r.fulfill({json:fixture});});await p.locator('#routing-provider').selectOption('ors');await p.locator('#calculate-route').click();await p.waitForFunction(()=>!planBusy);assert.equal(calls,2);assert.equal(await p.evaluate(()=>JSON.stringify(plannedStages)),oldGeometry);assert.match(await p.locator('#stops-status').innerText(),/Leg 2/);assert.equal(await p.locator('[data-stop]').count(),4);await p.locator('#routing-provider').selectOption('mapped');
 for(let i=0;i<20;i++){await p.locator('#append-hut').click();await p.locator('[data-stop]').last().selectOption(i%2?'nuvolau':'averau');}
 assert.equal(await p.locator('[data-stop]').count(),24);await p.waitForTimeout(350);await p.reload();await p.waitForFunction(()=>stopDraftReady&&localNetwork);await p.locator('#new-trip').click();assert.equal(await p.locator('[data-stop]').count(),24);await p.locator('#calculate-route').click();await p.waitForFunction(()=>!planBusy&&plannedStages.length===23);await p.locator('#save-route-plan').click();await p.waitForFunction(()=>trips[0].stages.length===23);assert.equal(await p.evaluate(()=>validStages(trips[0].stages)&&validPreferences(trips[0].preferences)),true);
 await p.reload();await p.waitForFunction(()=>storageReady&&localNetwork);await p.getByRole('button',{name:/My trips/}).click();await p.getByRole('button',{name:'View brief ↗',exact:true}).click();await p.locator('#restore-route').click();assert.equal(await p.locator('.stage-row').count(),23);assert.equal(await p.locator('[data-stop]').count(),24);assert.equal(await p.locator('.leaflet-overlay-pane path').count()>0,true);
 await p.locator('#browse-huts').click();await p.locator('#route-filter').selectOption('near');assert.equal(await p.locator('.hut').count()>0,true);await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('PASS: simple build/review navigation, route hover metrics and highlight, route click details, 46-hut catalogue, map markers, name search, destination switch, real 0.67 km route, unavailable elevation fallback, 23 connected stages with no two-hut limit, failed second leg preserves the previous plan, pending hut choices survive reload, save/reload and route restoration, corridor filter, mobile layout.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
