'use strict';
const $=id=>document.getElementById(id);
let huts=[
 {id:'cinque',name:'Rifugio Cinque Torri',height:'2,137 m',lat:46.5085,lng:12.0561,site:'https://www.rifugio5torri.it/',text:'At the foot of the iconic Five Towers, a natural starting point for exploring this small corner of the Dolomites.'},
 {id:'scoiattoli',name:'Rifugio Scoiattoli',height:'2,255 m',lat:46.5088,lng:12.0503,site:'https://www.rifugioscoiattoli.it/',text:'A panoramic terrace overlooking the Cinque Torri. Ask the operator about summer opening, rooms and current trail conditions.'},
 {id:'averau',name:'Rifugio Averau',height:'2,413 m',lat:46.4992,lng:12.0421,site:'https://www.rifugioaverau.it/',text:'Set below the rocky profile of Averau, with wide views across the mountains. Overnight availability needs direct confirmation.'},
 {id:'nuvolau',name:'Rifugio Nuvolau',height:'2,575 m',lat:46.4951,lng:12.0461,site:'https://rifugionuvolau.it/',text:'A summit hut with an exceptional mountain panorama. Walking approaches and via ferrata routes are distinct; this demo recommends neither.'}
];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,map,layer,markers=[],trips=[],step=0,editing=null,form={},storageReady=false;
const defaults=()=>({name:'My Dolomites escape',startDate:'2027-07-12',endDate:'2027-07-15',days:4,group:2,experience:'Intermediate',fitness:'Moderate',distance:12,hours:6,ascent:null,difficulty:'Marked hiking trails',scenery:['Panoramas'],accommodation:'Flexible',budget:100,startHut:'cinque'});
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function read(key){return req(db.transaction('data').objectStore('data').get(key));}
function write(key,value){return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function init(){try{const open=indexedDB.open('traversa-demo',1);open.onupgradeneeded=()=>open.result.createObjectStore('data');db=await req(open);trips=(await read('trips'))||[];storageReady=true;renderTrips();}catch{notify('Browser storage is unavailable. You can explore, but saving needs storage access.');}initMap();}
function notify(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,6500);}
function view(name){$('explore').hidden=name!=='explore';$('trips').hidden=name!=='trips';document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='explore')setTimeout(()=>map?.invalidateSize(),50);else renderTrips();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelector('.brand').onclick=e=>{e.preventDefault();view('explore');};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function initMap(){if(!window.L){$('map-message').hidden=false;$('map-message').textContent='The map library could not load. Hut details and trip planning are still available. Check your connection and reload.';return;}map=L.map('map',{zoomControl:false}).setView([46.502,12.048],14);L.control.zoom({position:'topright'}).addTo(map);setLayer('topo');huts.forEach((h,i)=>{const icon=L.divIcon({className:'hut-marker',html:'⌂',iconSize:[34,34],iconAnchor:[17,17]});const marker=L.marker([h.lat,h.lng],{icon,title:h.name,alt:h.name}).addTo(map).bindPopup(`<strong>${esc(h.name)}</strong><br>${h.height} · approximate location<br>Hut access not yet verified`);marker.on('click',()=>showHut(h.id));markers.push(marker);});}
const mapLayers={
 topo:{url:'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',max:17,attribution:'Map data © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, SRTM | Map style © <a href="https://opentopomap.org">OpenTopoMap</a> (CC-BY-SA)'},
 streets:{url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',max:18,attribution:'Tiles © Esri — Sources: Esri, HERE, Garmin, USGS, NGA, EPA, USDA, NPS'},
 satellite:{url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',max:18,attribution:'Tiles © Esri — Sources: Esri, Maxar, Earthstar Geographics and the GIS User Community'}
};
function setLayer(type){if(!map||!mapLayers[type])return;layer?.remove();$('map-message').hidden=true;let errors=0;const options=mapLayers[type];layer=L.tileLayer(options.url,{maxZoom:options.max,attribution:options.attribution}).addTo(map);const current=layer;layer.on('tileerror',()=>{if(current===layer&&++errors>3){$('map-message').hidden=false;$('map-message').textContent='Some map tiles are unavailable. Try another map layer or reload. Your trip is preserved.';}});layer.on('tileload',()=>{if(current===layer)$('map-message').hidden=true;});for(const id of Object.keys(mapLayers)){$(id).classList.toggle('selected',type===id);$(id).setAttribute('aria-pressed',String(type===id));}}
for(const id of Object.keys(mapLayers))$(id).onclick=()=>setLayer(id);
$('fit').onclick=()=>map?.fitBounds(huts.map(h=>[h.lat,h.lng]),{padding:[70,70]});
$('hut-list').innerHTML=huts.map((h,i)=>`<button class="hut" data-hut="${h.id}"><span class="hut-number">0${i+1}</span><span><strong>${h.name}</strong><small>${h.height} · Hut access under review</small></span><span class="arrow">↗</span></button>`).join('');
document.querySelectorAll('[data-hut]').forEach(b=>b.onclick=()=>{map?.flyTo([huts.find(h=>h.id===b.dataset.hut).lat,huts.find(h=>h.id===b.dataset.hut).lng],15);showHut(b.dataset.hut);});
function detail(title,eyebrow,body){$('detail-title').textContent=title;$('detail-eyebrow').textContent=eyebrow;$('detail-body').innerHTML=body;$('detail').showModal();}
function showHut(id){const h=huts.find(x=>x.id===id);detail(h.name,'DOLOMITES · MOUNTAIN HUT',`<p>${h.text}</p><div class="detail-facts"><div class="fact"><small>Reported hut elevation</small><strong>${h.height}</strong></div><div class="fact"><small>Map location</small><strong>Approximate · not an entrance</strong></div></div><div class="note"><strong>Confirm directly before you go</strong><p>Rooms, prices, seasonal opening and trail access have not been verified in this demo.</p></div><p><a href="${h.site}" target="_blank" rel="noopener noreferrer">Visit the hut operator’s website ↗</a></p><button class="primary" id="start-here">Start a brief here →</button>`);$('start-here').onclick=()=>{$('detail').close();openPlanner(null,id);};}
$('sources').onclick=()=>detail('A clear view of the data.','ABOUT THIS DEMO',`<p>Traversa starts with the Cinque Torri–Scoiattoli–Averau–Nuvolau group. This is an exploration and trip-brief demo, not a navigation tool.</p><div class="note"><strong>No invented hiking routes</strong><p>Hut markers are approximate orientation points. They are not surveyed entrances. No route lines, distances or walking times are calculated between them. Trails shown on the basemap belong to its provider and have not been reviewed by Traversa.</p></div><p>Hut information links to the respective operator. Topography is provided by OpenTopoMap with OpenStreetMap data and SRTM; street maps and satellite imagery are provided by Esri. Map tile availability depends on those providers.</p><p>Your briefs are saved in IndexedDB in this browser, not to a cloud account. Export backups before clearing browser data or changing devices. No API keys are collected and no AI generation is active.</p>`);
function label(text,name,type='text',extra=''){if(['distance','hours','budget'].includes(name))extra=extra.replace(/required/g,'')+' placeholder="Any"';return `<label>${text}<input name="${name}" type="${type}" value="${esc(form[name])}" ${extra}></label>`;}
function select(text,name,values){values=['Any',...values];return `<label>${text}<select name="${name}">${values.map(v=>`<option ${form[name]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
async function openPlanner(trip=null,hut=null){editing=trip?.id||null;form=trip?{...trip.preferences,scenery:[...trip.preferences.scenery]}:defaults();if(!trip&&storageReady){try{form=(await read('draft'))||form;}catch{notify('Could not restore your draft.');}}if(hut)form.startHut=hut;step=0;$('planner-title').textContent=trip?'Refine your mountain escape.':'Find your mountain rhythm.';renderForm();$('planner').showModal();}
$('new-trip').onclick=()=>openPlanner();
function renderForm(){document.querySelectorAll('.steps li').forEach((li,i)=>li.classList.toggle('current',i<=step));$('back').hidden=step===0;$('next').textContent=step===2?'Save trip brief ✓':'Continue →';let html='';if(step===0)html=`<h2>Where and when?</h2><p class="intro">Summer in the Dolomites. A plan at your own pace.</p><div class="form-grid"><div class="wide">${label('Trip name','name','text','required maxlength="100"')}</div>${label('Start date','startDate','date','required')}${label('End date','endDate','date',`required min="${form.startDate}"`)}${label('Hiking days','days','number','required min="1" max="10"')}${label('Group size','group','number','required min="1" max="20"')}</div>`;if(step===1)html=`<h2>How do you like to hike?</h2><p class="intro">These preferences guide your brief. They are not calculated route metrics.</p><div class="form-grid">${select('Experience','experience',['Beginner','Intermediate','Experienced'])}${select('Fitness','fitness',['Gentle','Moderate','Strong'])}${label('Maximum distance per day (km)','distance','number','required min="1" max="40"')}${label('Maximum walking hours per day','hours','number','required min="1" max="12" step="0.5"')}${select('Preferred terrain','difficulty',['Easy paths','Marked hiking trails','Demanding hiking trails'])}</div>`;if(step===2)html=`<h2>What draws you up here?</h2><p class="intro">Leave room for the things that make the journey yours.</p><label>Scenery preferences</label><div class="checks" style="margin:12px 0 24px">${['Any','Panoramas','Summits','Meadows','Forests','Lakes'].map(s=>`<label><input type="checkbox" name="scenery" value="${s}" ${(s==='Any'?form.scenery.length===0:form.scenery.includes(s))?'checked':''}>${s}</label>`).join('')}</div><div class="form-grid">${select('Accommodation preference','accommodation',['Flexible','Shared dormitory','Private room'])}${label('Budget per person per night (€)','budget','number','required min="0" max="1000"')}<label class="wide">Starting hut<select name="startHut">${huts.map(h=>`<option value="${h.id}" ${form.startHut===h.id?'selected':''}>${h.name}</option>`).join('')}</select></label></div><div class="note"><strong>A brief, not a route yet.</strong><p>Your preferences will be saved. Verified hut approaches are still missing, so no geographic itinerary, accommodation booking or AI result will be generated.</p></div>`;$('form-page').innerHTML=html;$('draft-status').textContent=storageReady?'Draft saved automatically':'Browser storage unavailable';}
function capture(){new FormData($('trip-form')).forEach((v,k)=>{if(k!=='scenery')form[k]=['distance','hours','ascent','budget'].includes(k)?(v===''?null:Number(v)):['days','group'].includes(k)?Number(v):v;});form.ascent=null;if(step===2)form.scenery=new FormData($('trip-form')).getAll('scenery').filter(s=>s!=='Any');}
let saving=Promise.resolve();$('trip-form').addEventListener('input',event=>{if(event.target.name==='scenery'){if(event.target.value==='Any'&&event.target.checked)document.querySelectorAll('[name="scenery"]').forEach(c=>{if(c.value!=='Any')c.checked=false;});else if(event.target.value!=='Any'&&event.target.checked)document.querySelector('[name="scenery"][value="Any"]').checked=false;}capture();if(step===0)$('trip-form').elements.endDate.min=form.startDate;if(!storageReady)return;$('draft-status').textContent='Saving draft…';const snapshot=structuredClone(form);saving=saving.catch(()=>{}).then(()=>write('draft',snapshot)).then(()=>{$('draft-status').textContent='Draft saved in this browser';}).catch(()=>{$('draft-status').textContent='Draft could not be saved';});});
$('back').onclick=()=>{capture();step--;renderForm();};
$('trip-form').onsubmit=async e=>{e.preventDefault();capture();if(step===0&&form.endDate<form.startDate){notify('End date must be on or after the start date.');return;}if(step<2){step++;renderForm();return;}if(!storageReady){notify('Saving requires browser storage. Please enable site storage and reload.');return;}const button=$('next');button.disabled=true;try{const now=new Date().toISOString(),old=trips.find(t=>t.id===editing);const trip={...old,id:editing||crypto.randomUUID(),createdAt:old?.createdAt||now,updatedAt:now,preferences:{...structuredClone(form),startHutName:huts.find(h=>h.id===form.startHut)?.name||form.startHutName}};const updated=editing?trips.map(t=>t.id===editing?trip:t):[trip,...trips];await saving;await write('trips',updated);trips=updated;await write('draft',null);$('planner').close();view('trips');notify(editing?'Trip brief updated.':'Your mountain escape is saved.');}catch{notify('Could not save your trip. Your form is still here; try again or export your existing briefs.');}finally{button.disabled=false;}};
function renderTrips(){$('trip-count').textContent=trips.length;$('trip-list').innerHTML=trips.length?trips.map(t=>{const p=t.preferences;return `<article class="trip-card"><div class="trip-cover">⌁<span>DOLOMITES, ITALY</span></div><div class="trip-body"><span class="pill">SAVED BRIEF</span><h2>${esc(p.name)}</h2><p>${esc(p.startDate)} → ${esc(p.endDate)}</p><div class="trip-meta"><div><strong>${p.days}</strong><small>hiking days</small></div><div><strong>${p.group}</strong><small>people</small></div><div><strong>${p.distance} km</strong><small>daily limit</small></div></div><p>No route generated · Hut access under review</p><div class="trip-actions"><button class="primary" data-action="open" data-id="${t.id}">View brief ↗</button><button class="outline" data-action="duplicate" data-id="${t.id}">Duplicate</button><button class="outline" data-action="delete" data-id="${t.id}">Delete</button></div></div></article>`;}).join(''):`<div class="empty"><div class="eyebrow">EVERY JOURNEY STARTS SOMEWHERE</div><h2>Your mountains are waiting.</h2><p>Create your first trip brief. Explore the huts, choose your dates,<br>and save the kind of journey you have in mind.</p><button class="primary" id="empty-new">Plan my first trip →</button></div>`;if($('empty-new'))$('empty-new').onclick=()=>openPlanner();document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>tripAction(b.dataset.action,b.dataset.id));}
async function persist(updated){if(!storageReady)throw Error('storage');await write('trips',updated);trips=updated;renderTrips();}
async function tripAction(action,id){const t=trips.find(x=>x.id===id);if(!t)return;if(action==='open')return showTrip(t);if(action==='duplicate'){try{const copy=structuredClone(t);copy.id=crypto.randomUUID();copy.preferences.name=copy.preferences.name.slice(0,90)+' (copy)';copy.createdAt=copy.updatedAt=new Date().toISOString();await persist([copy,...trips]);notify('Trip duplicated.');}catch{notify('Could not save the copy. Existing briefs are unchanged.');}}if(action==='delete'){detail('Delete this trip brief?','YOUR SAVED TRIPS',`<p>“${esc(t.preferences.name)}” will be removed from this browser. You can export a backup first.</p><button class="outline" id="cancel-delete">Keep trip</button> <button class="primary" id="confirm-delete">Delete brief</button>`);$('cancel-delete').onclick=()=>$('detail').close();$('confirm-delete').onclick=async()=>{try{await persist(trips.filter(x=>x.id!==id));$('detail').close();notify('Trip brief deleted.');}catch{notify('Could not delete the trip.');}};}}
function showTrip(t){const p=t.preferences;const facts={'Dates':p.startDate+' → '+p.endDate,'Hiking days':p.days,'Group size':p.group,'Starting hut':huts.find(h=>h.id===p.startHut)?.name||p.startHutName||p.startHut,'Experience / fitness':p.experience+' / '+p.fitness,'Daily limits':(p.distance===null?'Any distance':p.distance+' km')+' · '+(p.hours===null?'Any time':p.hours+' h'),'Terrain':p.difficulty,'Scenery':p.scenery.join(', ')||'Flexible','Accommodation':p.accommodation,'Budget / person / night':p.budget===null?'Any':'€'+p.budget};detail(p.name,'YOUR SAVED TRIP BRIEF',`<div class="detail-facts">${Object.entries(facts).map(([k,v])=>`<div class="fact"><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div><div class="note"><strong>Route generation is not available yet</strong><p>Verified hut-access geometry is required before stages, distance, ascent or hiking time can be calculated. These are your requested limits, not an itinerary.</p></div><button class="primary" id="edit-trip">Edit preferences</button> <button class="outline" id="export-one">Export this brief</button>`);$('edit-trip').onclick=()=>{$('detail').close();openPlanner(t);};$('export-one').onclick=()=>download([t]);}
function download(items){const url=URL.createObjectURL(new Blob([JSON.stringify({app:'traversa-demo',version:1,exportedAt:new Date().toISOString(),trips:items},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='traversa-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Backup downloaded. Keep it somewhere safe.');}
$('export').onclick=()=>{if(!trips.length)return notify('Create a trip brief first.');download(trips);};$('import').onclick=()=>$('import-file').click();
function validPreferences(p){return p&&typeof p.name==='string'&&p.name.trim().length>0&&p.name.length<=100&&['startDate','endDate'].every(k=>ItineraryCore.validDate(p[k]))&&p.endDate>=p.startDate&&[['days',1,Number.MAX_SAFE_INTEGER],['group',1,20],['distance',1,40],['hours',1,12],['ascent',100,3000],['budget',0,1000]].every(([k,min,max])=>p[k]===null&&['distance','hours','ascent','budget'].includes(k)||Number.isFinite(p[k])&&p[k]>=min&&p[k]<=max)&&Number.isInteger(p.days)&&Number.isInteger(p.group)&&['Any','Beginner','Intermediate','Experienced'].includes(p.experience)&&['Any','Gentle','Moderate','Strong'].includes(p.fitness)&&['Any','Easy paths','Marked hiking trails','Demanding hiking trails'].includes(p.difficulty)&&['Any','Flexible','Shared dormitory','Private room'].includes(p.accommodation)&&(p.routeDifficulty===undefined||['any','hiking','mountain_hiking','demanding_mountain_hiking'].includes(p.routeDifficulty))&&typeof p.startHut==='string'&&/^(cinque|scoiattoli|averau|nuvolau|osm-(node|way|relation)-[0-9]+)$/.test(p.startHut)&&Array.isArray(p.scenery)&&p.scenery.length<=5&&p.scenery.every(s=>['Panoramas','Summits','Meadows','Forests','Lakes'].includes(s));}
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>32000000)throw Error('Backup is too large (maximum 32 MB).');const data=JSON.parse(await file.text());if(data.app!=='traversa-demo'||data.version!==1)throw Error('This backup format is not supported.');if(!Array.isArray(data.trips)||!data.trips.length||data.trips.length>100||!data.trips.every(t=>t&&validPreferences(t.preferences)&&(!t.stages||validStages(t.stages))))throw Error('The backup contains invalid trip preferences.');const now=new Date().toISOString();const copies=data.trips.map(t=>({id:crypto.randomUUID(),createdAt:now,updatedAt:now,preferences:{...defaults(),...t.preferences,name:t.preferences.name.slice(0,89)+' (imported)'},...(t.stages?{stages:structuredClone(t.stages),importedRoute:true}:{})}));await persist([...copies,...trips]);notify(copies.length+' brief(s) imported as copies. Existing trips are preserved.');}catch(err){notify(err instanceof SyntaxError?'This file is not valid JSON. Existing trips are unchanged.':err.message||'Import failed. Existing trips are unchanged.');}finally{e.target.value='';}};
init();
