'use strict';
let comparisonLayer=null;
function clearRouteComparison(){comparisonLayer?.remove();comparisonLayer=null;}
function comparisonTable(original,alternative,error){
 const title=s=>s.provider==='ors'?'Openrouteservice':'Mapped OSM trails';const value=(s,key,suffix)=>Number.isFinite(s?.[key])?s[key].toFixed(key==='hours'?1:0)+suffix:'Unavailable';
 const rows=[['Distance',s=>s?(s.distanceM/1000).toFixed(2)+' km':'Unavailable'],['Hiking time',s=>value(s,'hours',' h estimated')],['Ascent',s=>value(s,'ascentM',' m estimated')],['Descent',s=>value(s,'descentM',' m estimated')],['Time method',s=>s?(s.provider==='ors'?'ORS walking-time estimate':'Naismith-style estimate'):'Unavailable'],['Recorded difficulty',s=>s?(s.unknownDifficulty?'Incomplete tags':s.difficulty||'Not recorded'):'Unavailable'],['Hut approach gaps',s=>s?Math.round(s.startGapM)+' m / '+Math.round(s.endGapM)+' m':'Unavailable']];
 return `<div class="comparison-scroll"><table class="comparison-table"><caption>Compare routes between the same two huts</caption><thead><tr><th scope="col">Measure</th><th scope="col">${title(original)}<small>Current route</small></th><th scope="col">${alternative?title(alternative):original.provider==='ors'?'Mapped OSM trails':'Openrouteservice'}<small>${alternative?'Alternative':'Unavailable'}</small></th></tr></thead><tbody>${rows.map(([label,display])=>`<tr><th scope="row">${label}</th><td>${esc(display(original))}</td><td>${esc(display(alternative))}</td></tr>`).join('')}</tbody></table></div>${error?`<p class="route-caution" role="alert">${esc(error)} Your existing route is unchanged.</p>`:''}<p class="intro">Providers may find the same trail. Their time and elevation estimates can differ. Hut approaches, restrictions and current conditions remain unreviewed.</p>`;
}
function addRouteComparison(stage){const index=plannedStages.indexOf(stage);if(index<0)return;$('route-result').insertAdjacentHTML('beforeend','<button class="outline full" id="compare-day-route">Compare ORS & mapped trails</button>');$('compare-day-route').disabled=planBusy;$('compare-day-route').onclick=()=>openRouteComparison(index);}
async function openRouteComparison(index){
 if(planBusy||!plannedStages[index])return;clearRouteComparison();const original=plannedStages[index],revision=planRevision,provider=original.provider==='ors'?'mapped':'ors';
 detail(original.start.name+' → '+original.end.name,'COMPARE THIS HIKING DAY','<p id="comparison-progress" role="status">Calculating the other provider’s route…</p><div id="comparison-content"></div>');const content=$('comparison-content');setPlanBusy(true);
 let alternative,error;try{alternative=await elevate({...await geometryFor(original.start,original.end,original.difficulty||$('route-difficulty').value,provider),start:original.start,end:original.end,difficulty:original.difficulty||$('route-difficulty').value});}catch(e){error=e.message;}finally{setPlanBusy(false);}
 if(!content.isConnected||!$('detail').open)return;
 $('comparison-progress').remove();if(planRevision!==revision||plannedStages[index]!==original){content.innerHTML='<p>Your trip changed. Close this comparison and compare the updated day.</p>';return;}
 const valid=()=>planRevision===revision&&plannedStages[index]===original;
 const use=()=>{if(planBusy||!valid())return notify('The trip changed. Compare this day again.');clearRouteComparison();const chosen={...alternative,restAfter:Boolean(original.restAfter),...(original.overnight?{overnight:structuredClone(original.overnight)}:{}),...(original.review?{review:structuredClone(original.review)}:{})};plannedStages=plannedStages.map((s,i)=>i===index?chosen:s);latestStage=chosen;routePlanChanged();renderPlannedStages();renderRouteMap();renderStage(chosen);$('add-stage').hidden=true;if($('detail').open)$('detail').close();notify('Route updated for this day. Rest days and booking notes kept. Save trip to keep the change.');};
 const actions=()=>{if($('use-alternative-route'))$('use-alternative-route').onclick=use;if($('preview-route-comparison'))$('preview-route-comparison').onclick=()=>{if(!valid())return notify('The trip changed. Compare this day again.');$('detail').close();latestStage=original;renderRouteMap();comparisonLayer=L.polyline(alternative.geometry.map(c=>[c[1],c[0]]),{color:'#7253aa',weight:6,dashArray:'8 6',opacity:1,className:'alternative-route'}).bindTooltip(esc(provider==='ors'?'ORS alternative':'Mapped alternative')+' · '+(alternative.distanceM/1000).toFixed(2)+' km').addTo(map);const bounds=routeLayer.getBounds().extend(comparisonLayer.getBounds());map.fitBounds(bounds,{padding:[65,75]});$('route-result').innerHTML=`<div class="stage-summary"><h2>Current route & alternative</h2><p>Current route: gold. Alternative: dashed purple.</p>${comparisonTable(original,alternative)}<button class="primary full" id="use-alternative-route">Use ${provider==='ors'?'ORS':'mapped'} route for this day</button><button class="outline full" id="cancel-route-comparison">Keep current route</button></div>`;$('use-alternative-route').onclick=use;$('cancel-route-comparison').onclick=()=>{clearRouteComparison();latestStage=original;renderStage(original);$('add-stage').hidden=true;};$('route-result').scrollIntoView({behavior:'smooth',block:'start'});};};
 content.innerHTML=comparisonTable(original,alternative,error)+(alternative?`<div class="travel-actions"><button class="outline" id="preview-route-comparison">Preview both on map</button><button class="primary" id="use-alternative-route">Use ${provider==='ors'?'ORS':'mapped'} route for this day</button></div>`:'');actions();
}
