'use strict';
let planBusy=false,planPreferences=defaults(),activeRouteTripId=null,planRevision=0,planDraftTimer=null,planDraftWrite=Promise.resolve();
function planCandidates(){const records=new Map(huts.map(h=>[h.id,h]));for(const s of plannedStages)for(const h of [s.start,s.end])records.set(h.id,h);return [...records.values()];}
function renderPlanSettings(){$('plan-settings').innerHTML=`<label>Trip name<input id="plan-name" value="${esc(planPreferences.name)}" maxlength="100" required></label><label>Start date<input id="plan-date" type="date" value="${esc(planPreferences.startDate)}" required></label><div class="filter-row"><label>Daily distance (km)<input id="plan-distance" type="number" min="1" max="40" step="0.5" value="${planPreferences.distance}" required></label><label>Daily time (h)<input id="plan-hours" type="number" min="1" max="12" step="0.5" value="${planPreferences.hours}" required></label></div><label>Daily ascent (m)<input id="plan-ascent" type="number" min="100" max="3000" step="50" value="${planPreferences.ascent}" required></label><p class="intro">Stage estimates are checked against these limits. Missing estimates stay unchecked.</p>`;for(const input of $('plan-settings').querySelectorAll('input'))input.oninput=()=>{if(!capturePlanSettings())return;routePlanChanged();renderPlannedStages();if(latestStage)renderStage(latestStage);};}
function capturePlanSettings(){const inputs=[...$('plan-settings').querySelectorAll('input')];if(inputs.some(input=>!input.checkValidity())||!$('plan-name').value.trim()){$('plan-draft-status').textContent='Complete the trip settings with valid values before saving.';return false;}planPreferences={...planPreferences,name:$('plan-name').value.trim(),startDate:$('plan-date').value,distance:Number($('plan-distance').value),hours:Number($('plan-hours').value),ascent:Number($('plan-ascent').value)};return true;}
function routePlanChanged(){planRevision++;clearTimeout(planDraftTimer);$('plan-draft-status').textContent=storageReady?'Saving route draft…':'Browser storage unavailable; export your plan.';if(!storageReady)return;const snapshot={stages:structuredClone(plannedStages),preferences:structuredClone(settingsFromPlan()),tripId:activeRouteTripId,startId:$('route-start').value};planDraftTimer=setTimeout(()=>{planDraftWrite=planDraftWrite.catch(()=>{}).then(()=>write('routeDraft',snapshot)).then(()=>{$('plan-draft-status').textContent='Route draft saved in this browser.';}).catch(()=>{$('plan-draft-status').textContent='Could not save the draft; export a backup.';});},200);}
function settingsFromPlan(){return {...planPreferences,days:Math.max(1,plannedStages.length),endDate:ItineraryCore.dateAt(planPreferences.startDate,Math.max(0,ItineraryCore.totals(plannedStages).calendarDays-1)),startHut:plannedStages[0]?.start.id||planPreferences.startHut,startHutName:plannedStages[0]?.start.name||planPreferences.startHutName};}
function stageWarnings(stage){return ItineraryCore.limits(stage,planPreferences);}
const baseRenderStage=renderStage;renderStage=function(stage){baseRenderStage(stage);updateRouteSelection();const warnings=stageWarnings(stage);if(warnings.length)$('route-result').querySelector('.stage-summary').insertAdjacentHTML('beforeend',`<div class="limit-warning" role="status"><strong>Check your daily limits</strong><ul>${warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`);};
function dayChecks(stage){
 const warnings=stageWarnings(stage),badges=[];
 if(warnings.some(w=>w.includes('exceeds')))badges.push('Over daily limits');
 if(!Number.isFinite(stage.hours)||!Number.isFinite(stage.ascentM))badges.push('Estimates missing');
 if(stage.unknownDifficulty)badges.push('Difficulty incomplete');
 return badges.length?`<div class="day-checks">${badges.map(label=>`<span>${label}</span>`).join('')}</div>`:'';
}
function renderTripOverview(){
 const el=$('trip-overview');el.hidden=!plannedStages.length;if(!plannedStages.length){el.innerHTML='';return;}
 const totals=ItineraryCore.totals(plannedStages),missingTime=plannedStages.filter(s=>!Number.isFinite(s.hours)).length,missingAscent=plannedStages.filter(s=>!Number.isFinite(s.ascentM)).length;
 const over=plannedStages.filter(s=>stageWarnings(s).some(w=>w.includes('exceeds'))).length,unknown=plannedStages.filter(s=>s.unknownDifficulty).length;
 const flags=[over?`${over} hiking ${over===1?'day exceeds':'days exceed'} your daily limits.`:'',missingTime?`Walking time missing on ${missingTime} ${missingTime===1?'day':'days'}; total time is incomplete.`:'',missingAscent?`Ascent missing on ${missingAscent} ${missingAscent===1?'day':'days'}; total ascent is incomplete.`:'',unknown?`Recorded difficulty is incomplete on ${unknown} ${unknown===1?'day':'days'}.`:''].filter(Boolean);
 el.innerHTML=`<div class="eyebrow">YOUR WHOLE JOURNEY</div><h2>${esc(planPreferences.name)}</h2><p class="overview-dates">${esc(planPreferences.startDate)} → ${esc(ItineraryCore.dateAt(planPreferences.startDate,totals.calendarDays-1))}<br>${plannedStages.length} hiking days · ${totals.calendarDays-plannedStages.length} rest ${totals.calendarDays-plannedStages.length===1?'day':'days'} · ${plannedStages.length+1} hut stops</p><div class="overview-metrics"><div><strong id="overview-distance">${(totals.distanceM/1000).toFixed(2)} km</strong><small>Total route distance</small></div><div><strong id="overview-hours">${totals.hours===null?'Incomplete':totals.hours.toFixed(1)+' h'}</strong><small>Estimated hiking time</small></div><div><strong id="overview-ascent">${totals.ascentM===null?'Incomplete':Math.round(totals.ascentM).toLocaleString()+' m'}</strong><small>Estimated ascent</small></div></div>${flags.length?`<details class="overview-checks"><summary>${flags.length} trip checks to review</summary><ul>${flags.map(flag=>`<li>${esc(flag)}</li>`).join('')}</ul></details>`:''}${overnightOverview()}<p class="overview-access">Hut approaches, current trail conditions and overnight availability still need checking.</p><button id="show-whole-trip" class="outline full">Show whole trip on map</button><div class="travel-actions"><button id="download-gpx" class="outline">Download GPX</button><button id="print-trip" class="outline">Print / offline itinerary</button></div><p class="travel-hint">Exports contain the calculated trip. Recalculate first if your hut choices changed.</p>`;
 bindTravelExports();
 $('show-whole-trip').onclick=()=>{latestStage=null;$('route-result').innerHTML='';updateRouteSelection();if(map&&routeLayer){const bounds=routeLayer.getBounds();for(const stage of plannedStages)for(const h of [stage.start,stage.end])bounds.extend([h.lat,h.lng]);map.fitBounds(bounds,{padding:[65,75]});}};
}
function setPlanBusy(busy){planBusy=busy;for(const id of ['calculate-route','clear-route','save-route-plan','remove-last-stage','route-start','route-end','destination','routing-provider','route-difficulty','download-gpx','print-trip'])if($(id))$(id).disabled=busy;document.querySelectorAll('[data-edit-stage],[data-rest-stage],[data-move-stage],[data-overnight]').forEach(b=>b.disabled=busy);document.querySelectorAll('#plan-settings input').forEach(input=>input.disabled=busy);}
renderPlannedStages=function(){
 const calendar=ItineraryCore.days(plannedStages,planPreferences.startDate),total=ItineraryCore.totals(plannedStages);
 $('stage-list').innerHTML=plannedStages.length?`<div class="itinerary-heading"><h2>Your day-by-day plan</h2><p>${plannedStages.length} hiking days · ${total.calendarDays} days including rest · ${(total.distanceM/1000).toFixed(2)} km</p></div>${calendar.map(day=>day.type==='rest'?`<div class="rest-day"><span>DAY ${day.day} · ${esc(day.date)}</span><strong>Rest at ${esc(day.hut.name)}</strong><small>No hiking stage · confirm the extra overnight directly</small><button class="text-button" data-rest-stage="${day.index}">Remove rest day</button></div>`:`<article class="stage-card"><button class="stage-row" data-stage="${day.index}"><span>DAY ${day.day} · ${esc(day.date)}</span><strong>${esc(day.stage.start.name)} → ${esc(day.stage.end.name)}</strong><small>${(day.stage.distanceM/1000).toFixed(2)} km · ${Number.isFinite(day.stage.hours)?day.stage.hours.toFixed(1)+' h estimated':'time unavailable'} · ${day.stage.provider==='ors'?'ORS':'mapped trails'}</small></button>${dayChecks(day.stage)}${overnightCard(day.index)}<div class="stage-edit-actions"><button class="outline" data-edit-stage="${day.index}">Replace overnight hut</button>${!day.stage.restAfter?`<button class="outline" data-rest-stage="${day.index}">Add rest day</button>`:''}${day.index>0?`<button class="outline" data-move-stage="${day.index}">Move overnight earlier</button>`:''}</div></article>`).join('')}<button class="outline full" id="remove-last-stage">Remove final stage</button><button class="primary full" id="save-route-plan">${activeRouteTripId?'Save changes to trip':'Save route preview'}</button><button class="text-button" id="export-route-plan">Export route plan JSON</button>`:'';
 bindOvernightControls();renderTripOverview();$('clear-route').hidden=!plannedStages.length;
 document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{latestStage=plannedStages[Number(b.dataset.stage)];renderStage(latestStage);$('add-stage').hidden=true;if(map)map.fitBounds(latestStage.geometry.map(c=>[c[1],c[0]]),{padding:[70,70]});});
 document.querySelectorAll('[data-edit-stage]').forEach(b=>b.onclick=()=>replaceHutDialog(Number(b.dataset.editStage)));
 document.querySelectorAll('[data-rest-stage]').forEach(b=>b.onclick=()=>{if(planBusy)return;const i=Number(b.dataset.restStage);plannedStages=plannedStages.map((s,index)=>index===i?{...s,restAfter:!s.restAfter}:s);latestStage=null;$('route-result').innerHTML='';routePlanChanged();renderPlannedStages();renderRouteMap();});
 document.querySelectorAll('[data-move-stage]').forEach(b=>b.onclick=()=>moveOvernightEarlier(Number(b.dataset.moveStage)));
 if($('save-route-plan'))$('save-route-plan').onclick=saveRoutePlan;
 if($('export-route-plan'))$('export-route-plan').onclick=()=>{if(!capturePlanSettings())return;download([{id:activeRouteTripId||crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),preferences:settingsFromPlan(),stages:plannedStages}]);};
 if($('remove-last-stage'))$('remove-last-stage').onclick=()=>{if(planBusy)return;plannedStages=plannedStages.slice(0,-1);latestStage=null;$('route-result').innerHTML='';if(plannedStages.length)$('route-start').value=plannedStages.at(-1).end.id;routePlanChanged();renderPlannedStages();renderRouteMap();renderCatalogue();};
 updateRouteSelection();setPlanBusy(planBusy);
};
async function rebuiltStage(original,start,end){if(start.id===end.id)throw Error('This change would create a stage with the same starting and ending hut.');const difficulty=original.difficulty||$('route-difficulty').value;const provider=original.provider==='ors'?'ors':'mapped';const geometry=await geometryFor(start,end,difficulty,provider);return {...await elevate({...geometry,start,end,difficulty}),restAfter:Boolean(original.restAfter),...(original.overnight?{overnight:original.overnight}:{})};}
async function applyStops(stops,restFlags){if(planBusy)return false;if(stops.length!==plannedStages.length+1)throw Error('Invalid overnight sequence.');setPlanBusy(true);const before=plannedStages;const revision=planRevision;try{const next=[];for(let i=0;i<before.length;i++){const start=stops[i],end=stops[i+1];const stage=before[i].start.id===start.id&&before[i].end.id===end.id?before[i]:await rebuiltStage(before[i],start,end);next.push({...stage,restAfter:Boolean(restFlags[i])});}if(!ItineraryCore.continuous(next))throw Error('The changed stages do not connect.');if(revision!==planRevision)throw Error('Your plan changed during calculation. Retry the edit.');plannedStages=next;latestStage=null;$('route-result').innerHTML='';$('route-start').value=next.at(-1).end.id;routePlanChanged();renderPlannedStages();renderRouteMap();renderCatalogue();return true;}finally{setPlanBusy(false);}}
function replaceHutDialog(index){if(planBusy)return;const stage=plannedStages[index];const choices=ItineraryCore.nearby(planCandidates().filter(h=>h.id!==stage.start.id&&h.id!==stage.end.id&&h.id!==plannedStages[index+1]?.end.id),stage.end);detail('Choose a different overnight hut','EDIT YOUR ITINERARY',`<p>Replacing ${esc(stage.end.name)} recalculates this stage${plannedStages[index+1]?' and the following stage':''}. Your current plan remains intact if a route cannot be found.</p><label>New overnight hut<select id="replacement-hut">${choices.map(h=>`<option value="${esc(h.id)}">${esc(h.name)} · ${(h.proximityM/1000).toFixed(2)} km from current overnight</option>`).join('')}</select></label><p class="intro">Proximity is straight-line distance. Reachability is checked when recalculating.</p><div class="note" id="replacement-status" role="status" hidden></div><button class="primary" id="replace-and-recalculate" ${choices.length?'':'disabled'}>Replace and recalculate</button>`);$('replace-and-recalculate').onclick=async()=>{const newHut=planCandidates().find(h=>h.id===$('replacement-hut').value);if(!newHut)return;const stops=[plannedStages[0].start,...plannedStages.map(s=>s.end)];const restFlags=plannedStages.map(s=>Boolean(s.restAfter));stops[index+1]=newHut;$('replace-and-recalculate').disabled=true;$('replacement-hut').disabled=true;const status=$('replacement-status');status.hidden=false;status.textContent='Recalculating affected stages…';try{if(await applyStops(stops,restFlags)){$('detail').close();notify('Overnight hut replaced; affected stages recalculated.');}}catch(e){status.textContent=e.message+' Your original plan has been kept.';}finally{if($('replace-and-recalculate'))$('replace-and-recalculate').disabled=false;if($('replacement-hut'))$('replacement-hut').disabled=false;}};}
async function moveOvernightEarlier(index){if(planBusy||index<1)return;const stops=[plannedStages[0].start,...plannedStages.map(s=>s.end)];[stops[index],stops[index+1]]=[stops[index+1],stops[index]];const restFlags=plannedStages.map(s=>Boolean(s.restAfter));[restFlags[index-1],restFlags[index]]=[restFlags[index],restFlags[index-1]];$('plan-draft-status').textContent='Recalculating reordered stages…';try{if(await applyStops(stops,restFlags))notify('Overnight order updated; affected stages recalculated.');}catch(e){notify(e.message+' The original plan is unchanged.');$('plan-draft-status').textContent='Reorder failed; original plan preserved.';}}
saveRoutePlan=async function(){if(planBusy||!plannedStages.length||!capturePlanSettings())return;if(!storageReady)return notify('Browser storage unavailable. Export your plan instead.');if(!ItineraryCore.continuous(plannedStages))return notify('Stages do not connect. Fix the overnight sequence before saving.');const now=new Date().toISOString();const old=trips.find(t=>t.id===activeRouteTripId);try{const t={...old,id:old?.id||crypto.randomUUID(),createdAt:old?.createdAt||now,updatedAt:now,preferences:settingsFromPlan(),stages:structuredClone(plannedStages)};await persist(old?trips.map(x=>x.id===old.id?t:x):[t,...trips]);activeRouteTripId=t.id;routePlanChanged();renderPlannedStages();notify(old?'Saved itinerary changes.':'Route preview saved.');}catch{notify('Could not save. Your on-screen plan is preserved; export a backup.');}};
const previousShowTrip=showTrip;showTrip=function(t){previousShowTrip(t);if($('restore-route'))$('restore-route').onclick=()=>{$('detail').close();plannedStages=structuredClone(t.stages);latestStage=null;planPreferences={...defaults(),...t.preferences};activeRouteTripId=t.id;view('explore');routeTabs(true);renderPlanSettings();renderPlannedStages();renderRouteMap();$('route-start').value=plannedStages.at(-1).end.id;renderCatalogue();routePlanChanged();};};
const previousValidStages=validStages;validStages=function(stages){return previousValidStages(stages)&&stages.every(s=>(s.restAfter===undefined||typeof s.restAfter==='boolean')&&ItineraryCore.validOvernight(s.overnight)&&[s.start,s.end].every(h=>Number.isFinite(h.lat)&&Number.isFinite(h.lng)&&h.lat>=46.05&&h.lat<=46.9&&h.lng>=11.25&&h.lng<=12.65));};
const previousClear=$('clear-route').onclick;$('clear-route').onclick=()=>{if(planBusy)return;previousClear();activeRouteTripId=null;planPreferences=defaults();renderPlanSettings();routePlanChanged();};
$('route-start').onchange=()=>{latestStage=null;$('route-result').innerHTML='';renderCatalogue();renderRouteMap();};
renderPlanSettings();
async function restoreRouteDraft(){const initial=planRevision;for(let tries=0;tries<100&&!storageReady;tries++)await new Promise(resolve=>setTimeout(resolve,20));if(!storageReady)return;try{const draft=await read('routeDraft');if(planRevision!==initial||!draft?.stages?.length||!validStages(draft.stages)||!validPreferences({...defaults(),...draft.preferences}))return;plannedStages=draft.stages;planPreferences={...defaults(),...draft.preferences};activeRouteTripId=trips.some(t=>t.id===draft.tripId)?draft.tripId:null;renderPlanSettings();renderPlannedStages();renderRouteMap();if(draft.startId&&huts.some(h=>h.id===draft.startId))$('route-start').value=draft.startId;renderCatalogue();$('plan-draft-status').textContent='Restored your unfinished route plan.';}catch{$('plan-draft-status').textContent='Could not restore the route draft. Saved trips remain available.';}}
restoreRouteDraft();
