(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ItineraryCore=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 function hutElevation(value){if(typeof value==='number')return Number.isFinite(value)?value:NaN;const text=String(value??'').trim().replace(/,(?=\d{3}(?:\D|$))/g,'');const match=text.match(/^(-?\d+(?:\.\d+)?)(?:\s*m)?$/);return match?Number(match[1]):NaN;}
 function distance(a,b){const rad=v=>v*Math.PI/180;const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
 function nearby(huts,start){return huts.map(h=>({...h,proximityM:start?distance(start,h):null})).sort((a,b)=>start?a.proximityM-b.proximityM||a.name.localeCompare(b.name):a.name.localeCompare(b.name));}
 function limits(stage,prefs){const warnings=[];if(Number.isFinite(prefs.distance)&&stage.distanceM/1000>prefs.distance)warnings.push(`Distance exceeds your ${prefs.distance} km daily limit.`);if(!Number.isFinite(stage.hours))warnings.push(Number.isFinite(prefs.hours)?'Walking time is unavailable; the time limit cannot be checked.':'Walking time is unavailable.');else if(Number.isFinite(prefs.hours)&&stage.hours>prefs.hours)warnings.push(`Estimated walking time exceeds your ${prefs.hours} h daily limit.`);if(!Number.isFinite(stage.ascentM))warnings.push(Number.isFinite(prefs.ascent)?'Ascent is unavailable; the ascent limit cannot be checked.':'Ascent is unavailable.');else if(Number.isFinite(prefs.ascent)&&stage.ascentM>prefs.ascent)warnings.push(`Estimated ascent exceeds your ${prefs.ascent} m daily limit.`);return warnings;}
 function validDate(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;}
 function dateAt(start,offset){if(!validDate(start)||!Number.isFinite(offset))return '';const d=new Date(start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);}
 function days(stages,startDate){const result=[];let day=1;for(let i=0;i<stages.length;i++){const s=stages[i];result.push({type:'hike',day,date:dateAt(startDate,day-1),index:i,stage:s});day++;if(s.restAfter){result.push({type:'rest',day,date:dateAt(startDate,day-1),index:i,hut:s.end});day++;}}return result;}
 function continuous(stages){return stages.every((s,i)=>s.start?.id!==s.end?.id&&(!i||stages[i-1].end.id===s.start.id));}
 function totals(stages){return {distanceM:stages.reduce((sum,s)=>sum+s.distanceM,0),hours:stages.every(s=>Number.isFinite(s.hours))?stages.reduce((sum,s)=>sum+s.hours,0):null,ascentM:stages.every(s=>Number.isFinite(s.ascentM))?stages.reduce((sum,s)=>sum+s.ascentM,0):null,calendarDays:stages.length+stages.filter(s=>s.restAfter).length};}
 function reconcileStages(next,before,preserveRest=true){
 const endVisits=new Map(),legVisits=new Map();for(const s of before){const end=s.end.id,key=JSON.stringify([s.start.id,end]);if(!endVisits.has(end))endVisits.set(end,[]);endVisits.get(end).push(s);if(!legVisits.has(key))legVisits.set(key,[]);legVisits.get(key).push(s);}
 const nextEnds=new Set(next.map(s=>s.end.id));
 return next.map((s,i)=>{const stay=endVisits.get(s.end.id)?.shift();const leg=legVisits.get(JSON.stringify([s.start.id,s.end.id]))?.shift();const replaced=!stay&&before[i]&&!nextEnds.has(before[i].end.id)?before[i]:null;const booking=(stay||replaced)?.overnight,review=(leg||stay||replaced)?.review;const {overnight:oldBooking,review:oldReview,...route}=s;return {...route,...(preserveRest?{restAfter:Boolean(stay?.restAfter)}:{}),...(booking?{overnight:structuredClone(booking)}:{}),...(review?{review:structuredClone(review)}:{})};});
 }
 function validOvernight(record){return record===undefined||Boolean(record&&['not_contacted','requested','confirmed'].includes(record.status)&&typeof record.hutId==='string'&&validDate(record.date)&&[1,2].includes(record.nights)&&typeof record.notes==='string'&&record.notes.length<=2000);}
 function overnight(stages,index,startDate){const stage=stages[index];const day=days(stages,startDate).find(d=>d.type==='hike'&&d.index===index);const context={hutId:stage.end.id,date:day.date,nights:stage.restAfter?2:1};const record=stage.overnight;const matches=validOvernight(record)&&record&&record.hutId===context.hutId&&record.date===context.date&&record.nights===context.nights;return {...context,status:matches?record.status:'not_contacted',notes:record?.notes||'',needsReview:Boolean(record&&!matches&&record.status!=='not_contacted')};}
 function reviewContext(stages,index,startDate){const s=stages[index];return JSON.stringify([days(stages,startDate).find(d=>d.type==='hike'&&d.index===index).date,s.start.id,s.end.id,s.provider,s.difficulty,s.geometry,s.startGapM,s.endGapM,s.unknownDifficulty]);}
 function validReview(r){return r===undefined||Boolean(r&&typeof r.context==='string'&&r.context.length<=2000000&&typeof r.notes==='string'&&r.notes.length<=2000&&typeof r.reviewedAt==='string'&&Number.isFinite(Date.parse(r.reviewedAt))&&r.checks&&['approach','difficulty','conditions'].every(k=>typeof r.checks[k]==='boolean'));}
 function review(stages,index,startDate){const context=reviewContext(stages,index,startDate),r=stages[index].review,matches=validReview(r)&&r&&r.context===context;const checks=matches?r.checks:{approach:false,difficulty:false,conditions:false};return {context,checks,count:['approach','difficulty','conditions'].filter(k=>checks[k]).length,notes:r?.notes||'',reviewedAt:matches?r.reviewedAt:'',needsReview:Boolean(r&&!matches)};}
 return {validDate,reconcileStages,hutElevation,reviewContext,validReview,review,distance,nearby,limits,dateAt,days,continuous,totals,validOvernight,overnight};
});
