(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ItineraryCore=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 function distance(a,b){const rad=v=>v*Math.PI/180;const dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const h=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
 function nearby(huts,start){return huts.map(h=>({...h,proximityM:start?distance(start,h):null})).sort((a,b)=>start?a.proximityM-b.proximityM||a.name.localeCompare(b.name):a.name.localeCompare(b.name));}
 function limits(stage,prefs){const warnings=[];if(stage.distanceM/1000>prefs.distance)warnings.push(`Distance exceeds your ${prefs.distance} km daily limit.`);if(!Number.isFinite(stage.hours))warnings.push('Walking time is unavailable; the time limit cannot be checked.');else if(stage.hours>prefs.hours)warnings.push(`Estimated walking time exceeds your ${prefs.hours} h daily limit.`);if(!Number.isFinite(stage.ascentM))warnings.push('Ascent is unavailable; the ascent limit cannot be checked.');else if(stage.ascentM>prefs.ascent)warnings.push(`Estimated ascent exceeds your ${prefs.ascent} m daily limit.`);return warnings;}
 function dateAt(start,offset){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!Number.isFinite(Date.parse(start)))return '';const d=new Date(start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);}
 function days(stages,startDate){const result=[];let day=1;for(let i=0;i<stages.length;i++){const s=stages[i];result.push({type:'hike',day,date:dateAt(startDate,day-1),index:i,stage:s});day++;if(s.restAfter){result.push({type:'rest',day,date:dateAt(startDate,day-1),index:i,hut:s.end});day++;}}return result;}
 function continuous(stages){return stages.every((s,i)=>s.start?.id!==s.end?.id&&(!i||stages[i-1].end.id===s.start.id));}
 function totals(stages){return {distanceM:stages.reduce((sum,s)=>sum+s.distanceM,0),hours:stages.every(s=>Number.isFinite(s.hours))?stages.reduce((sum,s)=>sum+s.hours,0):null,ascentM:stages.every(s=>Number.isFinite(s.ascentM))?stages.reduce((sum,s)=>sum+s.ascentM,0):null,calendarDays:stages.length+stages.filter(s=>s.restAfter).length};}
 return {distance,nearby,limits,dateAt,days,continuous,totals};
});
