'use strict';
function tripMode(review){$('build-panel').hidden=review;$('review-panel').hidden=!review;$('build-mode').classList.toggle('selected',!review);$('review-mode').classList.toggle('selected',review);$('route-result').innerHTML='';}
const simpleRouteTabs=routeTabs;routeTabs=function(routes){simpleRouteTabs(routes);$('discover-huts').hidden=routes;};
$('build-mode').onclick=()=>tripMode(false);$('review-mode').onclick=()=>tripMode(true);
$('new-trip').onclick=()=>{view('explore');routeTabs(true);tripMode(false);$('sidebar').scrollTop=0;$('route-start').focus();};
const simpleRenderPlan=renderPlannedStages;renderPlannedStages=function(){simpleRenderPlan();$('review-count').textContent=plannedStages.length;$('review-empty').hidden=!!plannedStages.length;$('build-heading').textContent=plannedStages.length?'Add your next hiking day':'1. Choose two huts';$('build-help').textContent=plannedStages.length?'Your last overnight hut is the next starting point. Choose where to stay next, then preview the route.':'Choose your starting hut and your first overnight stop. Preview the route, then add it to your trip.';document.querySelectorAll('.stage-edit-actions').forEach(actions=>{const disclosure=document.createElement('details');disclosure.className='day-options';disclosure.innerHTML='<summary>Edit this day</summary>';actions.replaceWith(disclosure);disclosure.append(actions);});const save=$('save-route-plan');if(save)save.textContent=activeRouteTripId?'Save trip changes':'Save trip';};
const simpleRenderStage=renderStage;renderStage=function(stage){simpleRenderStage(stage);const summary=$('route-result').querySelector('.stage-summary');const heading=summary.querySelector('.eyebrow');heading.textContent=plannedStages.includes(stage)?'DAY DETAILS':'2. PREVIEW YOUR DAY';const extra=document.createElement('details');extra.className='route-evidence';extra.innerHTML='<summary>Elevation, access & trail details</summary>';const first=summary.querySelector('.profile')||summary.querySelector('.route-metrics').nextElementSibling;let node=first;while(node&&node.id!=='add-stage'){const next=node.nextElementSibling;extra.append(node);node=next;}summary.insertBefore(extra,$('add-stage'));$('add-stage').textContent='3. Add this day to trip';const original=$('add-stage').onclick;$('add-stage').onclick=()=>{original();if(plannedStages.includes(stage)){tripMode(true);$('review-panel').scrollIntoView({behavior:'smooth',block:'start'});}};summary.insertAdjacentHTML('beforeend','<p class="route-caution">Route preview · hut access and current conditions still need checking.</p>');};
const simpleShowTrip=showTrip;showTrip=function(t){simpleShowTrip(t);const restore=$('restore-route');if(restore){const handler=restore.onclick;restore.textContent='Review and edit trip';restore.onclick=()=>{handler();tripMode(true);};}};
const simpleCalculate=$('calculate-route').onclick;$('calculate-route').onclick=async()=>{await simpleCalculate();$('calculate-route').textContent='Preview route →';};$('routing-provider').addEventListener('change',()=>{$('calculate-route').textContent='Preview route →';});$('calculate-route').textContent='Preview route →';
renderPlannedStages();
