'use strict';
const reviewLabels={approach:'I checked access to both huts, including the final approaches',difficulty:'I checked trail difficulty and suitability for my group',conditions:'I checked current trail conditions and closures for this date'};
function reviewCard(index){const r=ItineraryCore.review(plannedStages,index,planPreferences.startDate);return `<button class="outline full pretrip-card" data-review="${index}">Pre-trip review · ${r.needsReview?'Route or date changed — review again':r.count+' / 3 checks recorded'}</button>`;}
function reviewOverview(){const rows=plannedStages.map((s,i)=>ItineraryCore.review(plannedStages,i,planPreferences.startDate));return `<p class="overview-reviews"><strong>Your pre-trip review: ${rows.filter(r=>r.count===3).length} / ${rows.length} hiking days checked</strong><br><small>Personal tracking. Conditions are not checked by Traversa; revisit them before departure.</small></p>`;}
function bindReviewControls(){document.querySelectorAll('[data-review]').forEach(b=>{b.disabled=planBusy;b.onclick=()=>showReview(Number(b.dataset.review));});}
function showReview(index){const stage=plannedStages[index];if(!stage||planBusy)return;const r=ItineraryCore.review(plannedStages,index,planPreferences.startDate),day=ItineraryCore.days(plannedStages,planPreferences.startDate).find(d=>d.type==='hike'&&d.index===index);
 detail('Your pre-trip review','DAY '+day.day+' · '+day.date,`<h3>${esc(stage.start.name)} → ${esc(stage.end.name)}</h3>${r.needsReview?'<p class="route-caution">The route or hiking date changed. Review these checks again. Your previous notes are kept.</p>':''}<p>Use hut operators and current local trail reports to review this hiking day. Recording checks does not verify route safety or remove missing-data warnings.</p><p>Mapped approach gaps: ${Math.round(stage.startGapM)} m / ${Math.round(stage.endGapM)} m. ${stage.unknownDifficulty?'Recorded difficulty is incomplete.':'Recorded difficulty: '+esc(stage.difficulty||'unknown')+'.'}</p><div class="pretrip-checks">${Object.entries(reviewLabels).map(([key,label])=>`<label><input type="checkbox" id="review-${key}" ${r.checks[key]?'checked':''}>${label}</label>`).join('')}</div><label for="review-notes">Sources, dates checked and follow-up notes<textarea id="review-notes" rows="3" maxlength="2000" placeholder="For example: operator contacted, trail report date, questions still open…">${esc(r.notes)}</textarea></label>${r.reviewedAt?`<p class="intro">Last recorded: ${esc(r.reviewedAt)}</p>`:''}<p class="intro">Notes stay in your browser and JSON backups. Private notes are optional in printable itineraries.</p><button class="primary full" id="save-review">Save my review</button>`);
 $('save-review').onclick=()=>{if(planBusy||plannedStages[index]!==stage||ItineraryCore.reviewContext(plannedStages,index,planPreferences.startDate)!==r.context)return notify('The itinerary changed. Reopen this review before saving.');const checks=Object.fromEntries(Object.keys(reviewLabels).map(k=>[k,$('review-'+k).checked]));const selected=plannedStages.indexOf(latestStage);plannedStages=plannedStages.map((s,i)=>i===index?{...s,review:{context:r.context,checks,notes:$('review-notes').value.trim(),reviewedAt:new Date().toISOString()}}:s);if(selected>=0)latestStage=plannedStages[selected];routePlanChanged();renderPlannedStages();if(latestStage)renderStage(latestStage);$('detail').close();notify('Review saved to your draft. Save trip to update your saved trip.');};
}
