(function(root,factory){const core=typeof module==='object'&&module.exports?require('./itinerary-core'):root.ItineraryCore;const api=factory(core);if(typeof module==='object'&&module.exports)module.exports=api;else root.TripExport=api;})(typeof globalThis!=='undefined'?globalThis:this,core=>{
 const xml=value=>String(value??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
 const warning='Mapped trail preview. Hut approaches are unreviewed and excluded from route geometry. Check current trail conditions, difficulty and hut access before travel.';
 function gpx(stages,prefs){
 if(!stages.length||!core.continuous(stages))throw Error('Calculate a connected trip before exporting.');
 const days=core.days(stages,prefs.startDate).filter(d=>d.type==='hike');
 const stops=[stages[0].start,...stages.map(s=>s.end)];
 const waypoints=stops.map((h,i)=>`<wpt lat="${h.lat}" lon="${h.lng}"><name>${xml((i+1)+'. '+h.name)}</name><desc>Hut centre; entrance and final approach unreviewed.</desc></wpt>`).join('\n');
 const tracks=days.map(day=>{const s=day.stage;const sameElevation=s.provider==='ors'&&s.elevation?.length===s.geometry.length;return `<trk><name>${xml('Day '+day.day+': '+s.start.name+' → '+s.end.name)}</name><desc>${xml(day.date+' · '+warning+' Endpoint gaps: '+Math.round(s.startGapM)+' m and '+Math.round(s.endGapM)+' m.')}</desc><trkseg>${s.geometry.map((c,i)=>`<trkpt lat="${c[1]}" lon="${c[0]}">${sameElevation&&Number.isFinite(s.elevation[i])?'<ele>'+s.elevation[i]+'</ele>':''}</trkpt>`).join('')}</trkseg></trk>`;}).join('\n');
 return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Traversa" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${xml(prefs.name)}</name><desc>${xml(warning)}</desc></metadata>\n${waypoints}\n${tracks}\n</gpx>`;
 }
 const hutInfo=typeof module==='object'&&module.exports?require('./hut-info'):globalThis.HutInfo;
 const printStyle='body{font:14px system-ui,sans-serif;color:#203c32;max-width:850px;margin:32px auto;padding:0 24px}h1{font-size:28px}h2{font-size:18px}p,li{line-height:1.6}.export-warning{background:#fff1d5;padding:14px;border:1px solid #d1b56e}.export-day{border-top:1px solid #ccd4c8;margin-top:22px;padding-top:16px;break-inside:avoid}.export-notes{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#284e3e}small{color:#63705f}@media print{body{margin:0;max-width:none;padding:0}a{overflow-wrap:anywhere}@page{margin:16mm}}';
 function itinerary(stages,prefs,includeNotes=false){
 if(!stages.length)throw Error('Calculate your trip before exporting.');
 const total=core.totals(stages),days=core.days(stages,prefs.startDate),labels={not_contacted:'Not contacted',requested:'Requested',confirmed:'Marked confirmed by you'};
 const link=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
 const metrics=s=>`${(s.distanceM/1000).toFixed(2)} km · ${Number.isFinite(s.hours)?s.hours.toFixed(1)+' h estimated':'time unavailable'} · ↑ ${Number.isFinite(s.ascentM)?s.ascentM+' m estimated':'ascent unavailable'} · ↓ ${Number.isFinite(s.descentM)?s.descentM+' m estimated':'descent unavailable'} · ${s.provider==='ors'?'ORS':'mapped trails'}`;
 const rows=days.map(day=>{if(day.type==='rest')return `<section class="export-day"><h2>Day ${day.day} · ${xml(day.date)} · Rest at ${xml(day.hut.name)}</h2><p>No hiking stage. Extra overnight included in the preceding stay.</p></section>`;const s=day.stage,stay=core.overnight(stages,day.index,prefs.startDate),site=link(s.end.site),review=core.review(stages,day.index,prefs.startDate);return `<section class="export-day"><h2>Day ${day.day} · ${xml(day.date)}</h2><h3>${xml(s.start.name)} → ${xml(s.end.name)}</h3><p>${xml(metrics(s))}</p><p>Overnight: ${xml(s.end.name)} · ${stay.nights} ${stay.nights===1?'night':'nights'} · ${xml(stay.needsReview?'Stay changed — reconfirm':labels[stay.status])}</p><p>Your pre-trip review: ${review.needsReview?'Route or date changed — review again':review.count+' / 3 checks recorded'}${review.reviewedAt?' · '+xml(review.reviewedAt):''}. Personal tracking; current conditions are not checked by Traversa.</p><p>Approaches: ${review.checks.approach?'checked by you':'to review'} · Difficulty: ${review.checks.difficulty?'checked by you':'to review'} · Conditions: ${review.checks.conditions?'checked by you':'to review'}</p>${includeNotes&&review.notes?`<p class="export-notes"><strong>Your review notes</strong><br>${xml(review.notes)}</p>`:''}<p>Opening record: ${xml(hutInfo.opening(s.end.opening).lines.join(' · '))}</p><p>Facilities: ${xml(s.end.facilities||'Not recorded')}</p><p>Contact: ${xml(s.end.phone||'Not recorded')}${site?` · <a href="${xml(site)}">${xml(site)}</a>`:''}</p>${includeNotes&&stay.notes?`<p class="export-notes"><strong>Your booking notes</strong><br>${xml(stay.notes)}</p>`:''}<p><small>Hut approach gaps: ${Math.round(s.startGapM)} m / ${Math.round(s.endGapM)} m; not verified access.${s.unknownDifficulty?' Recorded difficulty is incomplete.':''}</small></p>${core.limits(s,prefs).length?`<ul>${core.limits(s,prefs).map(w=>`<li>${xml(w)}</li>`).join('')}</ul>`:''}</section>`;}).join('');
 const first=stages[0].start,descent=stages.every(s=>Number.isFinite(s.descentM))?stages.reduce((n,s)=>n+s.descentM,0):null;
 return `<article class="export-itinerary"><h1>${xml(prefs.name)}</h1><p>${xml(prefs.startDate)} → ${xml(core.dateAt(prefs.startDate,total.calendarDays-1))} · ${stages.length} hiking days · ${total.calendarDays-stages.length} rest days</p><p><strong>${(total.distanceM/1000).toFixed(2)} km</strong> · ${total.hours===null?'total time incomplete':total.hours.toFixed(1)+' h estimated'} · ${total.ascentM===null?'total ascent incomplete':Math.round(total.ascentM)+' m ascent estimated'} · ${descent===null?'total descent incomplete':Math.round(descent)+' m descent estimated'} · ${prefs.group||1} people</p><p class="export-warning">${xml(warning)} Overnight statuses are your own tracking, not independently verified reservations.</p><p>Start: ${xml(first.name)} · ${xml(first.phone||'Phone not recorded')}</p>${rows}<p><small>Route data: ${xml([...new Set(stages.map(s=>s.provider==='ors'?'openrouteservice / OpenStreetMap':'OpenStreetMap contributors (ODbL)'))].join(', '))}. This exported itinerary works without an internet connection; operator links need internet access.</small></p></article>`;
 }
 function html(stages,prefs,includeNotes=false){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${xml(prefs.name)} — itinerary</title><style>${printStyle}</style></head><body>${itinerary(stages,prefs,includeNotes)}</body></html>`;}
 return {gpx,itinerary,html};
});
